---

- name: Partition system
  parted:
    device: "{{ disk }}"
    number: 1
    flags: lvm
    state: present

- name: Install Arch Linux
  include: arch.yml
  when: base_os is match(".*Arch.*")